### ISSUE TITLE
User-Test auf IE11.0/Windows7 

### ISSUE THREAD

**Issue by bemattmann** [swissbib/pura-backend#1]
Wie gewünscht getestet und folgende Issues gefunden:

- [x] Wenn ich einen Account auf http://test.eduid.ch/ erstellen möchte und mich mit einer bereits bei Switch eingetragenen E-Mail-Adresse einen neuen Account erstellen möchte, erscheint korrekt eine Fehlermeldung. Klicke ich dann jedoch auf den Button "Zurück" gelange ich auf die About-Page.
- [x] Im Pura-Backend (https://shibdev.swissbib.ch/MyResearch/Pura) klappt der Login, im grafischen Template scheint allerdings die Positionierung des Switch-Logos ganz unten rechts nicht zu klappen. Es wird zur Hälfte ausserhalb der Textbox angezeigt.
- [x] Pura-Backend (https://shibdev.swissbib.ch/MyResearch/Pura): In der deutschen Version der Seite mit den Terms of Use heisst es im Titel "Nutzungsbedingungen" und am Ende der Seite "Ich akzeptiere die Benutzerordnung". Terminologie müsste einheitlich sein. Bei den anderen Sprachen ist dies der Fall.
- [x] Unter https://shibdev.swissbib.ch/MyResearch/Pura/library/A100 wird im Text auf das Akzeptieren der AGB's durch Vorweisen des Strichcodes am Schalter hingewiesen. Die AGB's sind dort jedoch nicht verlinkt.
- [x] Pura-Backend (http://pura.swissbib.ch/login): Wenn ich ohne Login die Menüpunkte "Activation" und "Control / Block" betätige funktioniert das zwar. Ich kann danach aber nicht mehr zurück zum Login. Idealerweise wäre dort ein zusätzlicher Menüpunkt oder der Seitentitel "PURA User Management" führt mich zurück zum Login (aktuell kein Link aktiv).
- [x] Pura-Backend (http://pura.swissbib.ch/purauser/edit): Wenn ich eingeloggt einen Nutzer suchen möchte, ist der Button "search user" inaktiv. Mit Betätigen der Enter-Taste springe ich irgendwohin, wohin ich wohl nicht springen dürfen sollte ... Aber das wisst ihr ja bereits.
- [x] Switch Attribute Viewer (https://wayf-test.switch.ch/aaitest/WAYF?entityID=https%3A%2F%2Fattribute-viewer.aai.switch.ch%2Fshibboleth&return=https%3A%2F%2Fattribute-viewer.aai.switch.ch%2FShibboleth.sso%2FDS-EW%3FSAMLDS%3D1): Dahin schaffe ich es nicht bzw. ein Login mit meinem Test-Account ist auch mit einem Privaten Tab in IE nicht möglich (Switch meldet unbekannten User). Ich vermute, dass ich da ausserhalb des Testsystems bin?

**Comment by liowalter** [comment]
> im grafischen Template scheint allerdings die Positionierung des Switch-Logos ganz unten rechts nicht zu klappen.

@beatmatt : can you add a screenshot ? I cannot reproduce that even on Internet Explorer.

**Comment by bemattmann** [comment]
@liowalter Ich musste mich nicht mal mehr einloggen, es zeigt sich schon auf dem Login-Screen:

![grafik](https://user-images.githubusercontent.com/31892836/38237985-ce75e41a-3728-11e8-9685-288a2d0cdb25.png)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [jhb](https://trello.com/c/pXWrXQNJ/48-jhb)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [522](https://trello.com/c/H4SHCb1I/88-522)
