### ISSUE TITLE
Beobachtungen nach Installation der Applikation

### ISSUE THREAD

**Issue by guenterh** [swissbib/pura-backend#2]
@edelm @liowalter 
- habe die Applikation heute morgen bei mir lokal installiert, einige Dinge sind mir aufgefallen
s. commit 81e04a5e731ce4e669030fe8deafe929506ff50d 

- ich bekomme nach dem Versuch der Anmeldung einen 500 server error. Ich möchte jetzt aber nicht einfach im debug mode zeile für zeile nachgehen sondern vorhandene devtools nutzen. 
Warum bekomme ich keine developer tool box angezeigt obwohl die Komponente installiert ist?
Warum startet die whoops komponente nach einem Fehler nicht obwohl installiert?

- https://github.com/swissbib/pura-backend/blob/master/config/pipeline.php#L10 werden mir bis Zeile 14 im phpstorm nicht aufgelöste Referenzen angezeigt. Warum?   
hier https://github.com/swissbib/pura-backend/blob/master/config/pipeline.php#L48 wird sich darauf bezogen. Höchst Fehleranfällig.

- https://github.com/swissbib/pura-backend/blob/master/module/App/src/Handler/HomePageHandler.php#L49 bitte keine String namespaces benutzen sondern Typ::class Notation (mit use Direktive)

**Comment by liowalter** [comment]
> Warum startet die whoops komponente nach einem Fehler nicht obwohl installiert?

Hast du `composer development-enable` gemacht ? More on that [here](https://github.com/swissbib/pura-backend/blob/master/config/development.config.php.dist#L8).

> Warum bekomme ich keine developer tool box angezeigt obwohl die Komponente installiert ist?

Das habe ich auch nicht.

**Comment by liowalter** [comment]
> Warum bekomme ich keine developer tool box angezeigt obwohl die Komponente installiert ist?

Zend Toolbar is only for MVC : https://github.com/zendframework/ZendDeveloperTools

Die installierte Komponente ist https://github.com/zendframework/zend-expressive-tooling. Die hat aber keine browser toolbar. 

Laut https://docs.zendframework.com/zend-expressive/v3/cookbook/debug-toolbars/ gibt es kein expressive dedicated toolbar. 

@guenterh : meintest du was anders ?

**Comment by guenterh** [comment]
Danke @liowalter    @edelm fyi 

Ich wusste nicht, dass dass Expressive diese Toolbar nicht unterstützt
Als Alternative geben sie das an https://docs.zendframework.com/zend-expressive/v3/cookbook/debug-toolbars/#php-middlewarephp-debug-bar   Kenne ich aber auch nicht. Ich fände gut, wenn wir solche tools vermehrt benutzen.

Die Cookbooks, von denen ich sprach, sind hier: https://drive.switch.ch/index.php/s/QSXhx4Sr3fueWj8 

Ich weiss im Moment nicht mehr wo ich sie heruntergeladen habe. Es war eine Stelle in der Zenddokumentation, die ich aber nicht finde. Expressive scheint noch in der Version 2 zu sein. Habe sie nur kurz überflogen. Schaue noch zu Hause auf meinem privaten Laptop nach, ob ich eine neuere Version finde.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [opoip](https://trello.com/c/jOOKIHaq/47-opoip)
